### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by tadeuszwachowski** [tadeuszwachowski/freya#1]
## User Story
As a customer, I want to reset my password so that I can regain access to my account.

### Tasks
- [x] Create a "Forgot Password" page with an email form
- [ ] Implement backend logic to generate a password reset token
- [x] Send an email to the user with the reset link
- [ ] Validate the token and allow the user to set a new password
- [ ] Write unit and integration tests for the reset password feature
